// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: kube_deploy.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubeDeployService_Deploy_FullMethodName              = "/kubedeploy.v1.KubeDeployService/Deploy"
	KubeDeployService_GetDeploymentStatus_FullMethodName = "/kubedeploy.v1.KubeDeployService/GetDeploymentStatus"
	KubeDeployService_ListDeployments_FullMethodName     = "/kubedeploy.v1.KubeDeployService/ListDeployments"
	KubeDeployService_Rollback_FullMethodName            = "/kubedeploy.v1.KubeDeployService/Rollback"
	KubeDeployService_WatchHealth_FullMethodName         = "/kubedeploy.v1.KubeDeployService/WatchHealth"
	KubeDeployService_GetHistory_FullMethodName          = "/kubedeploy.v1.KubeDeployService/GetHistory"
)

// KubeDeployServiceClient is the client API for KubeDeployService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KubeDeployServiceClient interface {
	// Deploy initiates a deployment and streams progress events back to the client.
	// The stream remains open until the deployment reaches a terminal state
	// (COMPLETED, FAILED, or ROLLED_BACK).
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployEvent], error)
	// GetDeploymentStatus returns the current state of a specific deployment.
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*DeploymentStatus, error)
	// ListDeployments returns all tracked deployments, optionally filtered
	// by namespace and label selectors.
	ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error)
	// Rollback triggers a manual rollback to a specific revision.
	// If target_revision is 0, it rolls back to the previous revision.
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// WatchHealth opens a server-streaming connection that continuously
	// emits health check results for the specified deployment.
	WatchHealth(ctx context.Context, in *WatchHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthEvent], error)
	// GetHistory retrieves the deployment revision history including
	// images, strategies used, and rollback events.
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
}

type kubeDeployServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeDeployServiceClient(cc grpc.ClientConnInterface) KubeDeployServiceClient {
	return &kubeDeployServiceClient{cc}
}

func (c *kubeDeployServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeDeployService_ServiceDesc.Streams[0], KubeDeployService_Deploy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeployRequest, DeployEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeDeployService_DeployClient = grpc.ServerStreamingClient[DeployEvent]

func (c *kubeDeployServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*DeploymentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentStatus)
	err := c.cc.Invoke(ctx, KubeDeployService_GetDeploymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeDeployServiceClient) ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeploymentsResponse)
	err := c.cc.Invoke(ctx, KubeDeployService_ListDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeDeployServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, KubeDeployService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeDeployServiceClient) WatchHealth(ctx context.Context, in *WatchHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeDeployService_ServiceDesc.Streams[1], KubeDeployService_WatchHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchHealthRequest, HealthEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeDeployService_WatchHealthClient = grpc.ServerStreamingClient[HealthEvent]

func (c *kubeDeployServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, KubeDeployService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeDeployServiceServer is the server API for KubeDeployService service.
// All implementations must embed UnimplementedKubeDeployServiceServer
// for forward compatibility.
type KubeDeployServiceServer interface {
	// Deploy initiates a deployment and streams progress events back to the client.
	// The stream remains open until the deployment reaches a terminal state
	// (COMPLETED, FAILED, or ROLLED_BACK).
	Deploy(*DeployRequest, grpc.ServerStreamingServer[DeployEvent]) error
	// GetDeploymentStatus returns the current state of a specific deployment.
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*DeploymentStatus, error)
	// ListDeployments returns all tracked deployments, optionally filtered
	// by namespace and label selectors.
	ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error)
	// Rollback triggers a manual rollback to a specific revision.
	// If target_revision is 0, it rolls back to the previous revision.
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// WatchHealth opens a server-streaming connection that continuously
	// emits health check results for the specified deployment.
	WatchHealth(*WatchHealthRequest, grpc.ServerStreamingServer[HealthEvent]) error
	// GetHistory retrieves the deployment revision history including
	// images, strategies used, and rollback events.
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	mustEmbedUnimplementedKubeDeployServiceServer()
}

// UnimplementedKubeDeployServiceServer must be embedded to have
// temporary forward compatible implementations.
type UnimplementedKubeDeployServiceServer struct{}

func (UnimplementedKubeDeployServiceServer) Deploy(*DeployRequest, grpc.ServerStreamingServer[DeployEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedKubeDeployServiceServer) GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*DeploymentStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (UnimplementedKubeDeployServiceServer) ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeployments not implemented")
}
func (UnimplementedKubeDeployServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedKubeDeployServiceServer) WatchHealth(*WatchHealthRequest, grpc.ServerStreamingServer[HealthEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchHealth not implemented")
}
func (UnimplementedKubeDeployServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedKubeDeployServiceServer) mustEmbedUnimplementedKubeDeployServiceServer() {}
func (UnimplementedKubeDeployServiceServer) testEmbeddedByValue()                           {}

// UnsafeKubeDeployServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeDeployServiceServer will
// result in compilation errors.
type UnsafeKubeDeployServiceServer interface {
	mustEmbedUnimplementedKubeDeployServiceServer()
}

func RegisterKubeDeployServiceServer(s grpc.ServiceRegistrar, srv KubeDeployServiceServer) {
	// If the following call panics, it indicates UnimplementedKubeDeployServiceServer was
	// temporary embedded by pointer and is not embedded by value.
	// Change the pointer to a value type to resolve this issue.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubeDeployService_ServiceDesc, srv)
}

func _KubeDeployService_Deploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeDeployServiceServer).Deploy(m, &grpc.GenericServerStream[DeployRequest, DeployEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeDeployService_DeployServer = grpc.ServerStreamingServer[DeployEvent]

func _KubeDeployService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeDeployServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeDeployService_GetDeploymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeDeployServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeDeployService_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeDeployServiceServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeDeployService_ListDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeDeployServiceServer).ListDeployments(ctx, req.(*ListDeploymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeDeployService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeDeployServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeDeployService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeDeployServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeDeployService_WatchHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeDeployServiceServer).WatchHealth(m, &grpc.GenericServerStream[WatchHealthRequest, HealthEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeDeployService_WatchHealthServer = grpc.ServerStreamingServer[HealthEvent]

func _KubeDeployService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeDeployServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeDeployService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeDeployServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KubeDeployService_ServiceDesc is the grpc.ServiceDesc for KubeDeployService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubeDeployService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubedeploy.v1.KubeDeployService",
	HandlerType: (*KubeDeployServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _KubeDeployService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _KubeDeployService_ListDeployments_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _KubeDeployService_Rollback_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _KubeDeployService_GetHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deploy",
			Handler:       _KubeDeployService_Deploy_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchHealth",
			Handler:       _KubeDeployService_WatchHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kube_deploy.proto",
}
