// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: kube_deploy.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================================
// Enums
// ============================================================================

type DeployStrategy int32

const (
	DeployStrategy_DEPLOY_STRATEGY_UNSPECIFIED DeployStrategy = 0
	DeployStrategy_DEPLOY_STRATEGY_ROLLING     DeployStrategy = 1
	DeployStrategy_DEPLOY_STRATEGY_CANARY      DeployStrategy = 2
	DeployStrategy_DEPLOY_STRATEGY_BLUE_GREEN  DeployStrategy = 3
)

func (x DeployStrategy) Enum() *DeployStrategy {
	p := new(DeployStrategy)
	*p = x
	return p
}

func (x DeployStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[0].Descriptor()
}

func (DeployStrategy) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[0]
}

func (x DeployStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (DeployStrategy) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{0}
}

type DeploymentPhase int32

const (
	DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED  DeploymentPhase = 0
	DeploymentPhase_DEPLOYMENT_PHASE_PENDING      DeploymentPhase = 1
	DeploymentPhase_DEPLOYMENT_PHASE_IN_PROGRESS  DeploymentPhase = 2
	DeploymentPhase_DEPLOYMENT_PHASE_HEALTH_CHECK DeploymentPhase = 3
	DeploymentPhase_DEPLOYMENT_PHASE_PROMOTING    DeploymentPhase = 4
	DeploymentPhase_DEPLOYMENT_PHASE_ROLLING_BACK DeploymentPhase = 5
	DeploymentPhase_DEPLOYMENT_PHASE_COMPLETED    DeploymentPhase = 6
	DeploymentPhase_DEPLOYMENT_PHASE_FAILED       DeploymentPhase = 7
	DeploymentPhase_DEPLOYMENT_PHASE_ROLLED_BACK  DeploymentPhase = 8
)

func (x DeploymentPhase) Enum() *DeploymentPhase {
	p := new(DeploymentPhase)
	*p = x
	return p
}

func (x DeploymentPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[1].Descriptor()
}

func (DeploymentPhase) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[1]
}

func (x DeploymentPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (DeploymentPhase) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{1}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 4
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{2}
}

type HealthCheckType int32

const (
	HealthCheckType_HEALTH_CHECK_TYPE_UNSPECIFIED   HealthCheckType = 0
	HealthCheckType_HEALTH_CHECK_TYPE_POD_READINESS HealthCheckType = 1
	HealthCheckType_HEALTH_CHECK_TYPE_RESTART_COUNT HealthCheckType = 2
	HealthCheckType_HEALTH_CHECK_TYPE_HTTP_PROBE    HealthCheckType = 3
	HealthCheckType_HEALTH_CHECK_TYPE_CUSTOM_METRIC HealthCheckType = 4
)

func (x HealthCheckType) Enum() *HealthCheckType {
	p := new(HealthCheckType)
	*p = x
	return p
}

func (x HealthCheckType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckType) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[3].Descriptor()
}

func (HealthCheckType) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[3]
}

func (x HealthCheckType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (HealthCheckType) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{3}
}

// ============================================================================
// Core Messages
// ============================================================================

type DeploymentTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace      string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	ContainerName  string `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image          string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *DeploymentTarget) Reset()         { *x = DeploymentTarget{} }
func (x *DeploymentTarget) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DeploymentTarget) ProtoMessage()  {}

func (x *DeploymentTarget) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DeploymentTarget) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentTarget) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeploymentTarget) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *DeploymentTarget) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *DeploymentTarget) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type RollingUpdateConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxUnavailable int32 `protobuf:"varint,1,opt,name=max_unavailable,json=maxUnavailable,proto3" json:"max_unavailable,omitempty"`
	MaxSurge       int32 `protobuf:"varint,2,opt,name=max_surge,json=maxSurge,proto3" json:"max_surge,omitempty"`
}

func (x *RollingUpdateConfig) Reset()         { *x = RollingUpdateConfig{} }
func (x *RollingUpdateConfig) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RollingUpdateConfig) ProtoMessage()  {}

func (x *RollingUpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RollingUpdateConfig) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *RollingUpdateConfig) GetMaxUnavailable() int32 {
	if x != nil {
		return x.MaxUnavailable
	}
	return 0
}

func (x *RollingUpdateConfig) GetMaxSurge() int32 {
	if x != nil {
		return x.MaxSurge
	}
	return 0
}

type CanaryConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanaryReplicas   int32                `protobuf:"varint,1,opt,name=canary_replicas,json=canaryReplicas,proto3" json:"canary_replicas,omitempty"`
	CanaryPercent    int32                `protobuf:"varint,2,opt,name=canary_percent,json=canaryPercent,proto3" json:"canary_percent,omitempty"`
	AnalysisDuration *durationpb.Duration `protobuf:"bytes,3,opt,name=analysis_duration,json=analysisDuration,proto3" json:"analysis_duration,omitempty"`
	SuccessThreshold int32                `protobuf:"varint,4,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	Steps            int32                `protobuf:"varint,5,opt,name=steps,proto3" json:"steps,omitempty"`
	StepWeights      []int32              `protobuf:"varint,6,rep,packed,name=step_weights,json=stepWeights,proto3" json:"step_weights,omitempty"`
}

func (x *CanaryConfig) Reset()         { *x = CanaryConfig{} }
func (x *CanaryConfig) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CanaryConfig) ProtoMessage()  {}

func (x *CanaryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CanaryConfig) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *CanaryConfig) GetCanaryReplicas() int32 {
	if x != nil {
		return x.CanaryReplicas
	}
	return 0
}

func (x *CanaryConfig) GetCanaryPercent() int32 {
	if x != nil {
		return x.CanaryPercent
	}
	return 0
}

func (x *CanaryConfig) GetAnalysisDuration() *durationpb.Duration {
	if x != nil {
		return x.AnalysisDuration
	}
	return nil
}

func (x *CanaryConfig) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *CanaryConfig) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *CanaryConfig) GetStepWeights() []int32 {
	if x != nil {
		return x.StepWeights
	}
	return nil
}

type RollbackPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled             bool                 `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxRetries          int32                `protobuf:"varint,2,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	HealthCheckInterval *durationpb.Duration `protobuf:"bytes,3,opt,name=health_check_interval,json=healthCheckInterval,proto3" json:"health_check_interval,omitempty"`
	HealthCheckTimeout  *durationpb.Duration `protobuf:"bytes,4,opt,name=health_check_timeout,json=healthCheckTimeout,proto3" json:"health_check_timeout,omitempty"`
	FailureThreshold    int32                `protobuf:"varint,5,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	SuccessThreshold    int32                `protobuf:"varint,6,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
}

func (x *RollbackPolicy) Reset()         { *x = RollbackPolicy{} }
func (x *RollbackPolicy) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RollbackPolicy) ProtoMessage()  {}

func (x *RollbackPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RollbackPolicy) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RollbackPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RollbackPolicy) GetHealthCheckInterval() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckInterval
	}
	return nil
}

func (x *RollbackPolicy) GetHealthCheckTimeout() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckTimeout
	}
	return nil
}

func (x *RollbackPolicy) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *RollbackPolicy) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

type HealthCheckConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             HealthCheckType      `protobuf:"varint,1,opt,name=type,proto3,enum=kubedeploy.v1.HealthCheckType" json:"type,omitempty"`
	HttpEndpoint     string               `protobuf:"bytes,2,opt,name=http_endpoint,json=httpEndpoint,proto3" json:"http_endpoint,omitempty"`
	Interval         *durationpb.Duration `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout          *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	FailureThreshold int32                `protobuf:"varint,5,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	SuccessThreshold int32                `protobuf:"varint,6,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	MaxRestartCount  int32                `protobuf:"varint,7,opt,name=max_restart_count,json=maxRestartCount,proto3" json:"max_restart_count,omitempty"`
}

func (x *HealthCheckConfig) Reset()         { *x = HealthCheckConfig{} }
func (x *HealthCheckConfig) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HealthCheckConfig) ProtoMessage()  {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckConfig) GetType() HealthCheckType {
	if x != nil {
		return x.Type
	}
	return HealthCheckType_HEALTH_CHECK_TYPE_UNSPECIFIED
}

func (x *HealthCheckConfig) GetHttpEndpoint() string {
	if x != nil {
		return x.HttpEndpoint
	}
	return ""
}

func (x *HealthCheckConfig) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *HealthCheckConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *HealthCheckConfig) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *HealthCheckConfig) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *HealthCheckConfig) GetMaxRestartCount() int32 {
	if x != nil {
		return x.MaxRestartCount
	}
	return 0
}

// ============================================================================
// Deploy RPC Messages
// ============================================================================

type DeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeployId       string               `protobuf:"bytes,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	Target         *DeploymentTarget    `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Strategy       DeployStrategy       `protobuf:"varint,3,opt,name=strategy,proto3,enum=kubedeploy.v1.DeployStrategy" json:"strategy,omitempty"`
	RollingConfig  *RollingUpdateConfig `protobuf:"bytes,4,opt,name=rolling_config,json=rollingConfig,proto3" json:"rolling_config,omitempty"`
	CanaryConfig   *CanaryConfig        `protobuf:"bytes,5,opt,name=canary_config,json=canaryConfig,proto3" json:"canary_config,omitempty"`
	RollbackPolicy *RollbackPolicy      `protobuf:"bytes,6,opt,name=rollback_policy,json=rollbackPolicy,proto3" json:"rollback_policy,omitempty"`
	HealthChecks   []*HealthCheckConfig `protobuf:"bytes,7,rep,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	Labels         map[string]string    `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations    map[string]string    `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DryRun         bool                 `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
}

func (x *DeployRequest) Reset()         { *x = DeployRequest{} }
func (x *DeployRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DeployRequest) ProtoMessage()  {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{5}
}

func (x *DeployRequest) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *DeployRequest) GetTarget() *DeploymentTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DeployRequest) GetStrategy() DeployStrategy {
	if x != nil {
		return x.Strategy
	}
	return DeployStrategy_DEPLOY_STRATEGY_UNSPECIFIED
}

func (x *DeployRequest) GetRollingConfig() *RollingUpdateConfig {
	if x != nil {
		return x.RollingConfig
	}
	return nil
}

func (x *DeployRequest) GetCanaryConfig() *CanaryConfig {
	if x != nil {
		return x.CanaryConfig
	}
	return nil
}

func (x *DeployRequest) GetRollbackPolicy() *RollbackPolicy {
	if x != nil {
		return x.RollbackPolicy
	}
	return nil
}

func (x *DeployRequest) GetHealthChecks() []*HealthCheckConfig {
	if x != nil {
		return x.HealthChecks
	}
	return nil
}

func (x *DeployRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeployRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *DeployRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type DeployEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeployId          string                 `protobuf:"bytes,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	Phase             DeploymentPhase        `protobuf:"varint,2,opt,name=phase,proto3,enum=kubedeploy.v1.DeploymentPhase" json:"phase,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReadyReplicas     int32                  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas   int32                  `protobuf:"varint,6,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	UpdatedReplicas   int32                  `protobuf:"varint,7,opt,name=updated_replicas,json=updatedReplicas,proto3" json:"updated_replicas,omitempty"`
	AvailableReplicas int32                  `protobuf:"varint,8,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	CurrentImage      string                 `protobuf:"bytes,9,opt,name=current_image,json=currentImage,proto3" json:"current_image,omitempty"`
	TargetImage       string                 `protobuf:"bytes,10,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	Revision          int64                  `protobuf:"varint,11,opt,name=revision,proto3" json:"revision,omitempty"`
	IsTerminal        bool                   `protobuf:"varint,12,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal,omitempty"`
	ErrorDetail       string                 `protobuf:"bytes,13,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
}

func (x *DeployEvent) Reset()         { *x = DeployEvent{} }
func (x *DeployEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DeployEvent) ProtoMessage()  {}

func (x *DeployEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DeployEvent) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{6}
}

func (x *DeployEvent) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *DeployEvent) GetPhase() DeploymentPhase {
	if x != nil {
		return x.Phase
	}
	return DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED
}

func (x *DeployEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DeployEvent) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *DeployEvent) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *DeployEvent) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

func (x *DeployEvent) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *DeployEvent) GetCurrentImage() string {
	if x != nil {
		return x.CurrentImage
	}
	return ""
}

func (x *DeployEvent) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *DeployEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeployEvent) GetIsTerminal() bool {
	if x != nil {
		return x.IsTerminal
	}
	return false
}

func (x *DeployEvent) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

// ============================================================================
// Status RPC Messages
// ============================================================================

type GetDeploymentStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace      string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
}

func (x *GetDeploymentStatusRequest) Reset()         { *x = GetDeploymentStatusRequest{} }
func (x *GetDeploymentStatusRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetDeploymentStatusRequest) ProtoMessage()  {}

func (x *GetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeploymentStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetDeploymentStatusRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

type DeploymentStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace         string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName    string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Phase             DeploymentPhase        `protobuf:"varint,3,opt,name=phase,proto3,enum=kubedeploy.v1.DeploymentPhase" json:"phase,omitempty"`
	CurrentImage      string                 `protobuf:"bytes,4,opt,name=current_image,json=currentImage,proto3" json:"current_image,omitempty"`
	ReadyReplicas     int32                  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas   int32                  `protobuf:"varint,6,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	UpdatedReplicas   int32                  `protobuf:"varint,7,opt,name=updated_replicas,json=updatedReplicas,proto3" json:"updated_replicas,omitempty"`
	AvailableReplicas int32                  `protobuf:"varint,8,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	CurrentRevision   int64                  `protobuf:"varint,9,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	HealthStatus      HealthStatus           `protobuf:"varint,10,opt,name=health_status,json=healthStatus,proto3,enum=kubedeploy.v1.HealthStatus" json:"health_status,omitempty"`
	LastUpdated       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Pods              []*PodStatus           `protobuf:"bytes,12,rep,name=pods,proto3" json:"pods,omitempty"`
	Conditions        []string               `protobuf:"bytes,13,rep,name=conditions,proto3" json:"conditions,omitempty"`
}

func (x *DeploymentStatus) Reset()         { *x = DeploymentStatus{} }
func (x *DeploymentStatus) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DeploymentStatus) ProtoMessage()  {}

func (x *DeploymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{8}
}

func (x *DeploymentStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeploymentStatus) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *DeploymentStatus) GetPhase() DeploymentPhase {
	if x != nil {
		return x.Phase
	}
	return DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED
}

func (x *DeploymentStatus) GetCurrentImage() string {
	if x != nil {
		return x.CurrentImage
	}
	return ""
}

func (x *DeploymentStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetCurrentRevision() int64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

func (x *DeploymentStatus) GetHealthStatus() HealthStatus {
	if x != nil {
		return x.HealthStatus
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *DeploymentStatus) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *DeploymentStatus) GetPods() []*PodStatus {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *DeploymentStatus) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type PodStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase        string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Ready        bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	RestartCount int32                  `protobuf:"varint,4,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	NodeName     string                 `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Image        string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	StartTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Message      string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PodStatus) Reset()         { *x = PodStatus{} }
func (x *PodStatus) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *PodStatus) ProtoMessage()  {}

func (x *PodStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*PodStatus) Descriptor() ([]byte, []int) { return file_kube_deploy_proto_rawDescGZIP(), []int{9} }

func (x *PodStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PodStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *PodStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *PodStatus) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PodStatus) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PodStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *PodStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ============================================================================
// List Deployments RPC Messages
// ============================================================================

type ListDeploymentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace     string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LabelSelector map[string]string `protobuf:"bytes,2,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListDeploymentsRequest) Reset()         { *x = ListDeploymentsRequest{} }
func (x *ListDeploymentsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ListDeploymentsRequest) ProtoMessage()  {}

func (x *ListDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{10}
}

func (x *ListDeploymentsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListDeploymentsRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

type ListDeploymentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployments []*DeploymentStatus `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
}

func (x *ListDeploymentsResponse) Reset()         { *x = ListDeploymentsResponse{} }
func (x *ListDeploymentsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ListDeploymentsResponse) ProtoMessage()  {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{11}
}

func (x *ListDeploymentsResponse) GetDeployments() []*DeploymentStatus {
	if x != nil {
		return x.Deployments
	}
	return nil
}

// ============================================================================
// Rollback RPC Messages
// ============================================================================

type RollbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace      string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	TargetRevision int64  `protobuf:"varint,3,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	Reason         string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *RollbackRequest) Reset()         { *x = RollbackRequest{} }
func (x *RollbackRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RollbackRequest) ProtoMessage()  {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RollbackRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *RollbackRequest) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *RollbackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RolledBackToRevision int64                  `protobuf:"varint,3,opt,name=rolled_back_to_revision,json=rolledBackToRevision,proto3" json:"rolled_back_to_revision,omitempty"`
	PreviousImage        string                 `protobuf:"bytes,4,opt,name=previous_image,json=previousImage,proto3" json:"previous_image,omitempty"`
	RestoredImage        string                 `protobuf:"bytes,5,opt,name=restored_image,json=restoredImage,proto3" json:"restored_image,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *RollbackResponse) Reset()         { *x = RollbackResponse{} }
func (x *RollbackResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RollbackResponse) ProtoMessage()  {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackResponse) GetRolledBackToRevision() int64 {
	if x != nil {
		return x.RolledBackToRevision
	}
	return 0
}

func (x *RollbackResponse) GetPreviousImage() string {
	if x != nil {
		return x.PreviousImage
	}
	return ""
}

func (x *RollbackResponse) GetRestoredImage() string {
	if x != nil {
		return x.RestoredImage
	}
	return ""
}

func (x *RollbackResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ============================================================================
// Health Watch RPC Messages
// ============================================================================

type WatchHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace      string               `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string               `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Interval       *durationpb.Duration `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Checks         []*HealthCheckConfig `protobuf:"bytes,4,rep,name=checks,proto3" json:"checks,omitempty"`
}

func (x *WatchHealthRequest) Reset()         { *x = WatchHealthRequest{} }
func (x *WatchHealthRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *WatchHealthRequest) ProtoMessage()  {}

func (x *WatchHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*WatchHealthRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{14}
}

func (x *WatchHealthRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchHealthRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *WatchHealthRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *WatchHealthRequest) GetChecks() []*HealthCheckConfig {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HealthEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	OverallStatus  HealthStatus           `protobuf:"varint,3,opt,name=overall_status,json=overallStatus,proto3,enum=kubedeploy.v1.HealthStatus" json:"overall_status,omitempty"`
	Results        []*HealthCheckResult   `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Summary        string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *HealthEvent) Reset()         { *x = HealthEvent{} }
func (x *HealthEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HealthEvent) ProtoMessage()  {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{15}
}

func (x *HealthEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HealthEvent) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *HealthEvent) GetOverallStatus() HealthStatus {
	if x != nil {
		return x.OverallStatus
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthEvent) GetResults() []*HealthCheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *HealthEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type HealthCheckResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      HealthCheckType        `protobuf:"varint,1,opt,name=type,proto3,enum=kubedeploy.v1.HealthCheckType" json:"type,omitempty"`
	Status    HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=kubedeploy.v1.HealthStatus" json:"status,omitempty"`
	Message   string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Target    string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Latency   *durationpb.Duration   `protobuf:"bytes,5,opt,name=latency,proto3" json:"latency,omitempty"`
	CheckedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Metadata  map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HealthCheckResult) Reset()         { *x = HealthCheckResult{} }
func (x *HealthCheckResult) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HealthCheckResult) ProtoMessage()  {}

func (x *HealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HealthCheckResult) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResult) GetType() HealthCheckType {
	if x != nil {
		return x.Type
	}
	return HealthCheckType_HEALTH_CHECK_TYPE_UNSPECIFIED
}

func (x *HealthCheckResult) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *HealthCheckResult) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *HealthCheckResult) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *HealthCheckResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ============================================================================
// History RPC Messages
// ============================================================================

type GetHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace      string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Limit          int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetHistoryRequest) Reset()         { *x = GetHistoryRequest{} }
func (x *GetHistoryRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetHistoryRequest) ProtoMessage()  {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{17}
}

func (x *GetHistoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetHistoryRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revisions []*DeploymentRevision `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
}

func (x *GetHistoryResponse) Reset()         { *x = GetHistoryResponse{} }
func (x *GetHistoryResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetHistoryResponse) ProtoMessage()  {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{18}
}

func (x *GetHistoryResponse) GetRevisions() []*DeploymentRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type DeploymentRevision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revision       int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Result         DeploymentPhase        `protobuf:"varint,3,opt,name=result,proto3,enum=kubedeploy.v1.DeploymentPhase" json:"result,omitempty"`
	Strategy       DeployStrategy         `protobuf:"varint,4,opt,name=strategy,proto3,enum=kubedeploy.v1.DeployStrategy" json:"strategy,omitempty"`
	DeployedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DeployedBy     string                 `protobuf:"bytes,7,opt,name=deployed_by,json=deployedBy,proto3" json:"deployed_by,omitempty"`
	RollbackReason string                 `protobuf:"bytes,8,opt,name=rollback_reason,json=rollbackReason,proto3" json:"rollback_reason,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Replicas       int32                  `protobuf:"varint,10,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *DeploymentRevision) Reset()         { *x = DeploymentRevision{} }
func (x *DeploymentRevision) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DeploymentRevision) ProtoMessage()  {}

func (x *DeploymentRevision) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DeploymentRevision) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{19}
}

func (x *DeploymentRevision) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeploymentRevision) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeploymentRevision) GetResult() DeploymentPhase {
	if x != nil {
		return x.Result
	}
	return DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED
}

func (x *DeploymentRevision) GetStrategy() DeployStrategy {
	if x != nil {
		return x.Strategy
	}
	return DeployStrategy_DEPLOY_STRATEGY_UNSPECIFIED
}

func (x *DeploymentRevision) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *DeploymentRevision) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *DeploymentRevision) GetDeployedBy() string {
	if x != nil {
		return x.DeployedBy
	}
	return ""
}

func (x *DeploymentRevision) GetRollbackReason() string {
	if x != nil {
		return x.RollbackReason
	}
	return ""
}

func (x *DeploymentRevision) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeploymentRevision) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

// ============================================================================
// File descriptor and registration
// ============================================================================

var file_kube_deploy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6b, 0x75, 0x62, 0x65, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e,
	0x76, 0x31,
}

var (
	file_kube_deploy_proto_rawDescOnce sync.Once
	file_kube_deploy_proto_rawDescData = file_kube_deploy_proto_rawDesc
)

func file_kube_deploy_proto_rawDescGZIP() []byte {
	file_kube_deploy_proto_rawDescOnce.Do(func() {
		file_kube_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(file_kube_deploy_proto_rawDescData)
	})
	return file_kube_deploy_proto_rawDescData
}

var file_kube_deploy_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_kube_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_kube_deploy_proto_goTypes = []interface{}{
	(DeployStrategy)(0),                // 0: kubedeploy.v1.DeployStrategy
	(DeploymentPhase)(0),               // 1: kubedeploy.v1.DeploymentPhase
	(HealthStatus)(0),                  // 2: kubedeploy.v1.HealthStatus
	(HealthCheckType)(0),               // 3: kubedeploy.v1.HealthCheckType
	(*DeploymentTarget)(nil),           // 4: kubedeploy.v1.DeploymentTarget
	(*RollingUpdateConfig)(nil),        // 5: kubedeploy.v1.RollingUpdateConfig
	(*CanaryConfig)(nil),               // 6: kubedeploy.v1.CanaryConfig
	(*RollbackPolicy)(nil),             // 7: kubedeploy.v1.RollbackPolicy
	(*HealthCheckConfig)(nil),          // 8: kubedeploy.v1.HealthCheckConfig
	(*DeployRequest)(nil),              // 9: kubedeploy.v1.DeployRequest
	(*DeployEvent)(nil),                // 10: kubedeploy.v1.DeployEvent
	(*GetDeploymentStatusRequest)(nil), // 11: kubedeploy.v1.GetDeploymentStatusRequest
	(*DeploymentStatus)(nil),           // 12: kubedeploy.v1.DeploymentStatus
	(*PodStatus)(nil),                  // 13: kubedeploy.v1.PodStatus
	(*ListDeploymentsRequest)(nil),     // 14: kubedeploy.v1.ListDeploymentsRequest
	(*ListDeploymentsResponse)(nil),    // 15: kubedeploy.v1.ListDeploymentsResponse
	(*RollbackRequest)(nil),            // 16: kubedeploy.v1.RollbackRequest
	(*RollbackResponse)(nil),           // 17: kubedeploy.v1.RollbackResponse
	(*WatchHealthRequest)(nil),         // 18: kubedeploy.v1.WatchHealthRequest
	(*HealthEvent)(nil),                // 19: kubedeploy.v1.HealthEvent
	(*HealthCheckResult)(nil),          // 20: kubedeploy.v1.HealthCheckResult
	(*GetHistoryRequest)(nil),          // 21: kubedeploy.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),         // 22: kubedeploy.v1.GetHistoryResponse
	(*DeploymentRevision)(nil),         // 23: kubedeploy.v1.DeploymentRevision
	nil,                                // 24-28: map entries
	(*durationpb.Duration)(nil),        // 29: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),      // 30: google.protobuf.Timestamp
}

func init() { file_kube_deploy_proto_init() }

func file_kube_deploy_proto_init() {
	if file_kube_deploy_proto_msgTypes[0].Exporter != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kube_deploy_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kube_deploy_proto_goTypes,
		DependencyIndexes: nil,
		EnumInfos:         file_kube_deploy_proto_enumTypes,
		MessageInfos:      file_kube_deploy_proto_msgTypes,
	}.Build()
	_ = out
}

// Ensure imports are used.
var (
	_ = durationpb.Duration{}
	_ = timestamppb.Timestamp{}
)
