// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: kube_deploy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployStrategy int32

const (
	DeployStrategy_DEPLOY_STRATEGY_UNSPECIFIED DeployStrategy = 0
	DeployStrategy_DEPLOY_STRATEGY_ROLLING     DeployStrategy = 1
	DeployStrategy_DEPLOY_STRATEGY_CANARY      DeployStrategy = 2
	DeployStrategy_DEPLOY_STRATEGY_BLUE_GREEN  DeployStrategy = 3
)

// Enum value maps for DeployStrategy.
var (
	DeployStrategy_name = map[int32]string{
		0: "DEPLOY_STRATEGY_UNSPECIFIED",
		1: "DEPLOY_STRATEGY_ROLLING",
		2: "DEPLOY_STRATEGY_CANARY",
		3: "DEPLOY_STRATEGY_BLUE_GREEN",
	}
	DeployStrategy_value = map[string]int32{
		"DEPLOY_STRATEGY_UNSPECIFIED": 0,
		"DEPLOY_STRATEGY_ROLLING":     1,
		"DEPLOY_STRATEGY_CANARY":      2,
		"DEPLOY_STRATEGY_BLUE_GREEN":  3,
	}
)

func (x DeployStrategy) Enum() *DeployStrategy {
	p := new(DeployStrategy)
	*p = x
	return p
}

func (x DeployStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[0].Descriptor()
}

func (DeployStrategy) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[0]
}

func (x DeployStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployStrategy.Descriptor instead.
func (DeployStrategy) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{0}
}

type DeploymentPhase int32

const (
	DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED  DeploymentPhase = 0
	DeploymentPhase_DEPLOYMENT_PHASE_PENDING      DeploymentPhase = 1
	DeploymentPhase_DEPLOYMENT_PHASE_IN_PROGRESS  DeploymentPhase = 2
	DeploymentPhase_DEPLOYMENT_PHASE_HEALTH_CHECK DeploymentPhase = 3
	DeploymentPhase_DEPLOYMENT_PHASE_PROMOTING    DeploymentPhase = 4
	DeploymentPhase_DEPLOYMENT_PHASE_ROLLING_BACK DeploymentPhase = 5
	DeploymentPhase_DEPLOYMENT_PHASE_COMPLETED    DeploymentPhase = 6
	DeploymentPhase_DEPLOYMENT_PHASE_FAILED       DeploymentPhase = 7
	DeploymentPhase_DEPLOYMENT_PHASE_ROLLED_BACK  DeploymentPhase = 8
)

// Enum value maps for DeploymentPhase.
var (
	DeploymentPhase_name = map[int32]string{
		0: "DEPLOYMENT_PHASE_UNSPECIFIED",
		1: "DEPLOYMENT_PHASE_PENDING",
		2: "DEPLOYMENT_PHASE_IN_PROGRESS",
		3: "DEPLOYMENT_PHASE_HEALTH_CHECK",
		4: "DEPLOYMENT_PHASE_PROMOTING",
		5: "DEPLOYMENT_PHASE_ROLLING_BACK",
		6: "DEPLOYMENT_PHASE_COMPLETED",
		7: "DEPLOYMENT_PHASE_FAILED",
		8: "DEPLOYMENT_PHASE_ROLLED_BACK",
	}
	DeploymentPhase_value = map[string]int32{
		"DEPLOYMENT_PHASE_UNSPECIFIED":  0,
		"DEPLOYMENT_PHASE_PENDING":      1,
		"DEPLOYMENT_PHASE_IN_PROGRESS":  2,
		"DEPLOYMENT_PHASE_HEALTH_CHECK": 3,
		"DEPLOYMENT_PHASE_PROMOTING":    4,
		"DEPLOYMENT_PHASE_ROLLING_BACK": 5,
		"DEPLOYMENT_PHASE_COMPLETED":    6,
		"DEPLOYMENT_PHASE_FAILED":       7,
		"DEPLOYMENT_PHASE_ROLLED_BACK":  8,
	}
)

func (x DeploymentPhase) Enum() *DeploymentPhase {
	p := new(DeploymentPhase)
	*p = x
	return p
}

func (x DeploymentPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[1].Descriptor()
}

func (DeploymentPhase) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[1]
}

func (x DeploymentPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentPhase.Descriptor instead.
func (DeploymentPhase) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{1}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 4
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
		4: "HEALTH_STATUS_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
		"HEALTH_STATUS_UNKNOWN":     4,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{2}
}

type HealthCheckType int32

const (
	HealthCheckType_HEALTH_CHECK_TYPE_UNSPECIFIED   HealthCheckType = 0
	HealthCheckType_HEALTH_CHECK_TYPE_POD_READINESS HealthCheckType = 1
	HealthCheckType_HEALTH_CHECK_TYPE_RESTART_COUNT HealthCheckType = 2
	HealthCheckType_HEALTH_CHECK_TYPE_HTTP_PROBE    HealthCheckType = 3
	HealthCheckType_HEALTH_CHECK_TYPE_CUSTOM_METRIC HealthCheckType = 4
)

// Enum value maps for HealthCheckType.
var (
	HealthCheckType_name = map[int32]string{
		0: "HEALTH_CHECK_TYPE_UNSPECIFIED",
		1: "HEALTH_CHECK_TYPE_POD_READINESS",
		2: "HEALTH_CHECK_TYPE_RESTART_COUNT",
		3: "HEALTH_CHECK_TYPE_HTTP_PROBE",
		4: "HEALTH_CHECK_TYPE_CUSTOM_METRIC",
	}
	HealthCheckType_value = map[string]int32{
		"HEALTH_CHECK_TYPE_UNSPECIFIED":   0,
		"HEALTH_CHECK_TYPE_POD_READINESS": 1,
		"HEALTH_CHECK_TYPE_RESTART_COUNT": 2,
		"HEALTH_CHECK_TYPE_HTTP_PROBE":    3,
		"HEALTH_CHECK_TYPE_CUSTOM_METRIC": 4,
	}
)

func (x HealthCheckType) Enum() *HealthCheckType {
	p := new(HealthCheckType)
	*p = x
	return p
}

func (x HealthCheckType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckType) Descriptor() protoreflect.EnumDescriptor {
	return file_kube_deploy_proto_enumTypes[3].Descriptor()
}

func (HealthCheckType) Type() protoreflect.EnumType {
	return &file_kube_deploy_proto_enumTypes[3]
}

func (x HealthCheckType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckType.Descriptor instead.
func (HealthCheckType) EnumDescriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{3}
}

type DeploymentTarget struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	ContainerName  string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image          string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeploymentTarget) Reset() {
	*x = DeploymentTarget{}
	mi := &file_kube_deploy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentTarget) ProtoMessage() {}

func (x *DeploymentTarget) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentTarget.ProtoReflect.Descriptor instead.
func (*DeploymentTarget) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentTarget) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeploymentTarget) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *DeploymentTarget) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *DeploymentTarget) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type RollingUpdateConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxUnavailable int32                  `protobuf:"varint,1,opt,name=max_unavailable,json=maxUnavailable,proto3" json:"max_unavailable,omitempty"`
	MaxSurge       int32                  `protobuf:"varint,2,opt,name=max_surge,json=maxSurge,proto3" json:"max_surge,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollingUpdateConfig) Reset() {
	*x = RollingUpdateConfig{}
	mi := &file_kube_deploy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollingUpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollingUpdateConfig) ProtoMessage() {}

func (x *RollingUpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollingUpdateConfig.ProtoReflect.Descriptor instead.
func (*RollingUpdateConfig) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *RollingUpdateConfig) GetMaxUnavailable() int32 {
	if x != nil {
		return x.MaxUnavailable
	}
	return 0
}

func (x *RollingUpdateConfig) GetMaxSurge() int32 {
	if x != nil {
		return x.MaxSurge
	}
	return 0
}

type CanaryConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CanaryReplicas   int32                  `protobuf:"varint,1,opt,name=canary_replicas,json=canaryReplicas,proto3" json:"canary_replicas,omitempty"`
	CanaryPercent    int32                  `protobuf:"varint,2,opt,name=canary_percent,json=canaryPercent,proto3" json:"canary_percent,omitempty"`
	AnalysisDuration *durationpb.Duration   `protobuf:"bytes,3,opt,name=analysis_duration,json=analysisDuration,proto3" json:"analysis_duration,omitempty"`
	SuccessThreshold int32                  `protobuf:"varint,4,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	Steps            int32                  `protobuf:"varint,5,opt,name=steps,proto3" json:"steps,omitempty"`
	StepWeights      []int32                `protobuf:"varint,6,rep,packed,name=step_weights,json=stepWeights,proto3" json:"step_weights,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CanaryConfig) Reset() {
	*x = CanaryConfig{}
	mi := &file_kube_deploy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanaryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanaryConfig) ProtoMessage() {}

func (x *CanaryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanaryConfig.ProtoReflect.Descriptor instead.
func (*CanaryConfig) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *CanaryConfig) GetCanaryReplicas() int32 {
	if x != nil {
		return x.CanaryReplicas
	}
	return 0
}

func (x *CanaryConfig) GetCanaryPercent() int32 {
	if x != nil {
		return x.CanaryPercent
	}
	return 0
}

func (x *CanaryConfig) GetAnalysisDuration() *durationpb.Duration {
	if x != nil {
		return x.AnalysisDuration
	}
	return nil
}

func (x *CanaryConfig) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *CanaryConfig) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *CanaryConfig) GetStepWeights() []int32 {
	if x != nil {
		return x.StepWeights
	}
	return nil
}

type RollbackPolicy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxRetries          int32                  `protobuf:"varint,2,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	HealthCheckInterval *durationpb.Duration   `protobuf:"bytes,3,opt,name=health_check_interval,json=healthCheckInterval,proto3" json:"health_check_interval,omitempty"`
	HealthCheckTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=health_check_timeout,json=healthCheckTimeout,proto3" json:"health_check_timeout,omitempty"`
	FailureThreshold    int32                  `protobuf:"varint,5,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	SuccessThreshold    int32                  `protobuf:"varint,6,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RollbackPolicy) Reset() {
	*x = RollbackPolicy{}
	mi := &file_kube_deploy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPolicy) ProtoMessage() {}

func (x *RollbackPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPolicy.ProtoReflect.Descriptor instead.
func (*RollbackPolicy) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RollbackPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RollbackPolicy) GetHealthCheckInterval() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckInterval
	}
	return nil
}

func (x *RollbackPolicy) GetHealthCheckTimeout() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckTimeout
	}
	return nil
}

func (x *RollbackPolicy) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *RollbackPolicy) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

type HealthCheckConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             HealthCheckType        `protobuf:"varint,1,opt,name=type,proto3,enum=kubedeploy.v1.HealthCheckType" json:"type,omitempty"`
	HttpEndpoint     string                 `protobuf:"bytes,2,opt,name=http_endpoint,json=httpEndpoint,proto3" json:"http_endpoint,omitempty"`
	Interval         *durationpb.Duration   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout          *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	FailureThreshold int32                  `protobuf:"varint,5,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	SuccessThreshold int32                  `protobuf:"varint,6,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	MaxRestartCount  int32                  `protobuf:"varint,7,opt,name=max_restart_count,json=maxRestartCount,proto3" json:"max_restart_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckConfig) Reset() {
	*x = HealthCheckConfig{}
	mi := &file_kube_deploy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckConfig) ProtoMessage() {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckConfig.ProtoReflect.Descriptor instead.
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckConfig) GetType() HealthCheckType {
	if x != nil {
		return x.Type
	}
	return HealthCheckType_HEALTH_CHECK_TYPE_UNSPECIFIED
}

func (x *HealthCheckConfig) GetHttpEndpoint() string {
	if x != nil {
		return x.HttpEndpoint
	}
	return ""
}

func (x *HealthCheckConfig) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *HealthCheckConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *HealthCheckConfig) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *HealthCheckConfig) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *HealthCheckConfig) GetMaxRestartCount() int32 {
	if x != nil {
		return x.MaxRestartCount
	}
	return 0
}

type DeployRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeployId       string                 `protobuf:"bytes,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	Target         *DeploymentTarget      `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Strategy       DeployStrategy         `protobuf:"varint,3,opt,name=strategy,proto3,enum=kubedeploy.v1.DeployStrategy" json:"strategy,omitempty"`
	RollingConfig  *RollingUpdateConfig   `protobuf:"bytes,4,opt,name=rolling_config,json=rollingConfig,proto3" json:"rolling_config,omitempty"`
	CanaryConfig   *CanaryConfig          `protobuf:"bytes,5,opt,name=canary_config,json=canaryConfig,proto3" json:"canary_config,omitempty"`
	RollbackPolicy *RollbackPolicy        `protobuf:"bytes,6,opt,name=rollback_policy,json=rollbackPolicy,proto3" json:"rollback_policy,omitempty"`
	HealthChecks   []*HealthCheckConfig   `protobuf:"bytes,7,rep,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations    map[string]string      `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DryRun         bool                   `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_kube_deploy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{5}
}

func (x *DeployRequest) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *DeployRequest) GetTarget() *DeploymentTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DeployRequest) GetStrategy() DeployStrategy {
	if x != nil {
		return x.Strategy
	}
	return DeployStrategy_DEPLOY_STRATEGY_UNSPECIFIED
}

func (x *DeployRequest) GetRollingConfig() *RollingUpdateConfig {
	if x != nil {
		return x.RollingConfig
	}
	return nil
}

func (x *DeployRequest) GetCanaryConfig() *CanaryConfig {
	if x != nil {
		return x.CanaryConfig
	}
	return nil
}

func (x *DeployRequest) GetRollbackPolicy() *RollbackPolicy {
	if x != nil {
		return x.RollbackPolicy
	}
	return nil
}

func (x *DeployRequest) GetHealthChecks() []*HealthCheckConfig {
	if x != nil {
		return x.HealthChecks
	}
	return nil
}

func (x *DeployRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeployRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *DeployRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type DeployEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeployId          string                 `protobuf:"bytes,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	Phase             DeploymentPhase        `protobuf:"varint,2,opt,name=phase,proto3,enum=kubedeploy.v1.DeploymentPhase" json:"phase,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReadyReplicas     int32                  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas   int32                  `protobuf:"varint,6,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	UpdatedReplicas   int32                  `protobuf:"varint,7,opt,name=updated_replicas,json=updatedReplicas,proto3" json:"updated_replicas,omitempty"`
	AvailableReplicas int32                  `protobuf:"varint,8,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	CurrentImage      string                 `protobuf:"bytes,9,opt,name=current_image,json=currentImage,proto3" json:"current_image,omitempty"`
	TargetImage       string                 `protobuf:"bytes,10,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	Revision          int64                  `protobuf:"varint,11,opt,name=revision,proto3" json:"revision,omitempty"`
	IsTerminal        bool                   `protobuf:"varint,12,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal,omitempty"`
	ErrorDetail       string                 `protobuf:"bytes,13,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeployEvent) Reset() {
	*x = DeployEvent{}
	mi := &file_kube_deploy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployEvent) ProtoMessage() {}

func (x *DeployEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployEvent.ProtoReflect.Descriptor instead.
func (*DeployEvent) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{6}
}

func (x *DeployEvent) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *DeployEvent) GetPhase() DeploymentPhase {
	if x != nil {
		return x.Phase
	}
	return DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED
}

func (x *DeployEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DeployEvent) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *DeployEvent) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *DeployEvent) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

func (x *DeployEvent) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *DeployEvent) GetCurrentImage() string {
	if x != nil {
		return x.CurrentImage
	}
	return ""
}

func (x *DeployEvent) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *DeployEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeployEvent) GetIsTerminal() bool {
	if x != nil {
		return x.IsTerminal
	}
	return false
}

func (x *DeployEvent) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type GetDeploymentStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeploymentStatusRequest) Reset() {
	*x = GetDeploymentStatusRequest{}
	mi := &file_kube_deploy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusRequest) ProtoMessage() {}

func (x *GetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeploymentStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetDeploymentStatusRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

type DeploymentStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Namespace         string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName    string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Phase             DeploymentPhase        `protobuf:"varint,3,opt,name=phase,proto3,enum=kubedeploy.v1.DeploymentPhase" json:"phase,omitempty"`
	CurrentImage      string                 `protobuf:"bytes,4,opt,name=current_image,json=currentImage,proto3" json:"current_image,omitempty"`
	ReadyReplicas     int32                  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas   int32                  `protobuf:"varint,6,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	UpdatedReplicas   int32                  `protobuf:"varint,7,opt,name=updated_replicas,json=updatedReplicas,proto3" json:"updated_replicas,omitempty"`
	AvailableReplicas int32                  `protobuf:"varint,8,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	CurrentRevision   int64                  `protobuf:"varint,9,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	HealthStatus      HealthStatus           `protobuf:"varint,10,opt,name=health_status,json=healthStatus,proto3,enum=kubedeploy.v1.HealthStatus" json:"health_status,omitempty"`
	LastUpdated       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Pods              []*PodStatus           `protobuf:"bytes,12,rep,name=pods,proto3" json:"pods,omitempty"`
	Conditions        []string               `protobuf:"bytes,13,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeploymentStatus) Reset() {
	*x = DeploymentStatus{}
	mi := &file_kube_deploy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatus) ProtoMessage() {}

func (x *DeploymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatus.ProtoReflect.Descriptor instead.
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{8}
}

func (x *DeploymentStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeploymentStatus) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *DeploymentStatus) GetPhase() DeploymentPhase {
	if x != nil {
		return x.Phase
	}
	return DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED
}

func (x *DeploymentStatus) GetCurrentImage() string {
	if x != nil {
		return x.CurrentImage
	}
	return ""
}

func (x *DeploymentStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *DeploymentStatus) GetCurrentRevision() int64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

func (x *DeploymentStatus) GetHealthStatus() HealthStatus {
	if x != nil {
		return x.HealthStatus
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *DeploymentStatus) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *DeploymentStatus) GetPods() []*PodStatus {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *DeploymentStatus) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type PodStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	RestartCount  int32                  `protobuf:"varint,4,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	NodeName      string                 `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatus) Reset() {
	*x = PodStatus{}
	mi := &file_kube_deploy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatus) ProtoMessage() {}

func (x *PodStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatus.ProtoReflect.Descriptor instead.
func (*PodStatus) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{9}
}

func (x *PodStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PodStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *PodStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *PodStatus) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PodStatus) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PodStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *PodStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LabelSelector map[string]string      `protobuf:"bytes,2,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsRequest) Reset() {
	*x = ListDeploymentsRequest{}
	mi := &file_kube_deploy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsRequest) ProtoMessage() {}

func (x *ListDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{10}
}

func (x *ListDeploymentsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListDeploymentsRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

type ListDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*DeploymentStatus    `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResponse) Reset() {
	*x = ListDeploymentsResponse{}
	mi := &file_kube_deploy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResponse) ProtoMessage() {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{11}
}

func (x *ListDeploymentsResponse) GetDeployments() []*DeploymentStatus {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type RollbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	TargetRevision int64                  `protobuf:"varint,3,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_kube_deploy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RollbackRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *RollbackRequest) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *RollbackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RollbackResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RolledBackToRevision int64                  `protobuf:"varint,3,opt,name=rolled_back_to_revision,json=rolledBackToRevision,proto3" json:"rolled_back_to_revision,omitempty"`
	PreviousImage        string                 `protobuf:"bytes,4,opt,name=previous_image,json=previousImage,proto3" json:"previous_image,omitempty"`
	RestoredImage        string                 `protobuf:"bytes,5,opt,name=restored_image,json=restoredImage,proto3" json:"restored_image,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_kube_deploy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackResponse) GetRolledBackToRevision() int64 {
	if x != nil {
		return x.RolledBackToRevision
	}
	return 0
}

func (x *RollbackResponse) GetPreviousImage() string {
	if x != nil {
		return x.PreviousImage
	}
	return ""
}

func (x *RollbackResponse) GetRestoredImage() string {
	if x != nil {
		return x.RestoredImage
	}
	return ""
}

func (x *RollbackResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WatchHealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Interval       *durationpb.Duration   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Checks         []*HealthCheckConfig   `protobuf:"bytes,4,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchHealthRequest) Reset() {
	*x = WatchHealthRequest{}
	mi := &file_kube_deploy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchHealthRequest) ProtoMessage() {}

func (x *WatchHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchHealthRequest.ProtoReflect.Descriptor instead.
func (*WatchHealthRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{14}
}

func (x *WatchHealthRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchHealthRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *WatchHealthRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *WatchHealthRequest) GetChecks() []*HealthCheckConfig {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HealthEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	OverallStatus  HealthStatus           `protobuf:"varint,3,opt,name=overall_status,json=overallStatus,proto3,enum=kubedeploy.v1.HealthStatus" json:"overall_status,omitempty"`
	Results        []*HealthCheckResult   `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Summary        string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthEvent) Reset() {
	*x = HealthEvent{}
	mi := &file_kube_deploy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvent) ProtoMessage() {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvent.ProtoReflect.Descriptor instead.
func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{15}
}

func (x *HealthEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HealthEvent) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *HealthEvent) GetOverallStatus() HealthStatus {
	if x != nil {
		return x.OverallStatus
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthEvent) GetResults() []*HealthCheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *HealthEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type HealthCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          HealthCheckType        `protobuf:"varint,1,opt,name=type,proto3,enum=kubedeploy.v1.HealthCheckType" json:"type,omitempty"`
	Status        HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=kubedeploy.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Latency       *durationpb.Duration   `protobuf:"bytes,5,opt,name=latency,proto3" json:"latency,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResult) Reset() {
	*x = HealthCheckResult{}
	mi := &file_kube_deploy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResult) ProtoMessage() {}

func (x *HealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResult.ProtoReflect.Descriptor instead.
func (*HealthCheckResult) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResult) GetType() HealthCheckType {
	if x != nil {
		return x.Type
	}
	return HealthCheckType_HEALTH_CHECK_TYPE_UNSPECIFIED
}

func (x *HealthCheckResult) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *HealthCheckResult) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *HealthCheckResult) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *HealthCheckResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName string                 `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_kube_deploy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{17}
}

func (x *GetHistoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetHistoryRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*DeploymentRevision  `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_kube_deploy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{18}
}

func (x *GetHistoryResponse) GetRevisions() []*DeploymentRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type DeploymentRevision struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Revision       int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Result         DeploymentPhase        `protobuf:"varint,3,opt,name=result,proto3,enum=kubedeploy.v1.DeploymentPhase" json:"result,omitempty"`
	Strategy       DeployStrategy         `protobuf:"varint,4,opt,name=strategy,proto3,enum=kubedeploy.v1.DeployStrategy" json:"strategy,omitempty"`
	DeployedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DeployedBy     string                 `protobuf:"bytes,7,opt,name=deployed_by,json=deployedBy,proto3" json:"deployed_by,omitempty"`
	RollbackReason string                 `protobuf:"bytes,8,opt,name=rollback_reason,json=rollbackReason,proto3" json:"rollback_reason,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Replicas       int32                  `protobuf:"varint,10,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeploymentRevision) Reset() {
	*x = DeploymentRevision{}
	mi := &file_kube_deploy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentRevision) ProtoMessage() {}

func (x *DeploymentRevision) ProtoReflect() protoreflect.Message {
	mi := &file_kube_deploy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentRevision.ProtoReflect.Descriptor instead.
func (*DeploymentRevision) Descriptor() ([]byte, []int) {
	return file_kube_deploy_proto_rawDescGZIP(), []int{19}
}

func (x *DeploymentRevision) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeploymentRevision) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeploymentRevision) GetResult() DeploymentPhase {
	if x != nil {
		return x.Result
	}
	return DeploymentPhase_DEPLOYMENT_PHASE_UNSPECIFIED
}

func (x *DeploymentRevision) GetStrategy() DeployStrategy {
	if x != nil {
		return x.Strategy
	}
	return DeployStrategy_DEPLOY_STRATEGY_UNSPECIFIED
}

func (x *DeploymentRevision) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *DeploymentRevision) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *DeploymentRevision) GetDeployedBy() string {
	if x != nil {
		return x.DeployedBy
	}
	return ""
}

func (x *DeploymentRevision) GetRollbackReason() string {
	if x != nil {
		return x.RollbackReason
	}
	return ""
}

func (x *DeploymentRevision) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeploymentRevision) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

var File_kube_deploy_proto protoreflect.FileDescriptor

const file_kube_deploy_proto_rawDesc = "" +
	"\n" +
	"\x11kube_deploy.proto\x12\rkubedeploy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x96\x01\n" +
	"\x10DeploymentTarget\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\"[\n" +
	"\x13RollingUpdateConfig\x12'\n" +
	"\x0fmax_unavailable\x18\x01 \x01(\x05R\x0emaxUnavailable\x12\x1b\n" +
	"\tmax_surge\x18\x02 \x01(\x05R\bmaxSurge\"\x8c\x02\n" +
	"\fCanaryConfig\x12'\n" +
	"\x0fcanary_replicas\x18\x01 \x01(\x05R\x0ecanaryReplicas\x12%\n" +
	"\x0ecanary_percent\x18\x02 \x01(\x05R\rcanaryPercent\x12F\n" +
	"\x11analysis_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10analysisDuration\x12+\n" +
	"\x11success_threshold\x18\x04 \x01(\x05R\x10successThreshold\x12\x14\n" +
	"\x05steps\x18\x05 \x01(\x05R\x05steps\x12!\n" +
	"\fstep_weights\x18\x06 \x03(\x05R\vstepWeights\"\xc1\x02\n" +
	"\x0eRollbackPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vmax_retries\x18\x02 \x01(\x05R\n" +
	"maxRetries\x12M\n" +
	"\x15health_check_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x13healthCheckInterval\x12K\n" +
	"\x14health_check_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x12healthCheckTimeout\x12+\n" +
	"\x11failure_threshold\x18\x05 \x01(\x05R\x10failureThreshold\x12+\n" +
	"\x11success_threshold\x18\x06 \x01(\x05R\x10successThreshold\"\xde\x02\n" +
	"\x11HealthCheckConfig\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.kubedeploy.v1.HealthCheckTypeR\x04type\x12#\n" +
	"\rhttp_endpoint\x18\x02 \x01(\tR\fhttpEndpoint\x125\n" +
	"\binterval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\binterval\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12+\n" +
	"\x11failure_threshold\x18\x05 \x01(\x05R\x10failureThreshold\x12+\n" +
	"\x11success_threshold\x18\x06 \x01(\x05R\x10successThreshold\x12*\n" +
	"\x11max_restart_count\x18\a \x01(\x05R\x0fmaxRestartCount\"\xe3\x05\n" +
	"\rDeployRequest\x12\x1b\n" +
	"\tdeploy_id\x18\x01 \x01(\tR\bdeployId\x127\n" +
	"\x06target\x18\x02 \x01(\v2\x1f.kubedeploy.v1.DeploymentTargetR\x06target\x129\n" +
	"\bstrategy\x18\x03 \x01(\x0e2\x1d.kubedeploy.v1.DeployStrategyR\bstrategy\x12I\n" +
	"\x0erolling_config\x18\x04 \x01(\v2\".kubedeploy.v1.RollingUpdateConfigR\rrollingConfig\x12@\n" +
	"\rcanary_config\x18\x05 \x01(\v2\x1b.kubedeploy.v1.CanaryConfigR\fcanaryConfig\x12F\n" +
	"\x0frollback_policy\x18\x06 \x01(\v2\x1d.kubedeploy.v1.RollbackPolicyR\x0erollbackPolicy\x12E\n" +
	"\rhealth_checks\x18\a \x03(\v2 .kubedeploy.v1.HealthCheckConfigR\fhealthChecks\x12@\n" +
	"\x06labels\x18\b \x03(\v2(.kubedeploy.v1.DeployRequest.LabelsEntryR\x06labels\x12O\n" +
	"\vannotations\x18\t \x03(\v2-.kubedeploy.v1.DeployRequest.AnnotationsEntryR\vannotations\x12\x17\n" +
	"\adry_run\x18\n" +
	" \x01(\bR\x06dryRun\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x04\n" +
	"\vDeployEvent\x12\x1b\n" +
	"\tdeploy_id\x18\x01 \x01(\tR\bdeployId\x124\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x1e.kubedeploy.v1.DeploymentPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0eready_replicas\x18\x05 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10desired_replicas\x18\x06 \x01(\x05R\x0fdesiredReplicas\x12)\n" +
	"\x10updated_replicas\x18\a \x01(\x05R\x0fupdatedReplicas\x12-\n" +
	"\x12available_replicas\x18\b \x01(\x05R\x11availableReplicas\x12#\n" +
	"\rcurrent_image\x18\t \x01(\tR\fcurrentImage\x12!\n" +
	"\ftarget_image\x18\n" +
	" \x01(\tR\vtargetImage\x12\x1a\n" +
	"\brevision\x18\v \x01(\x03R\brevision\x12\x1f\n" +
	"\vis_terminal\x18\f \x01(\bR\n" +
	"isTerminal\x12!\n" +
	"\ferror_detail\x18\r \x01(\tR\verrorDetail\"c\n" +
	"\x1aGetDeploymentStatusRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\"\xda\x04\n" +
	"\x10DeploymentStatus\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x124\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x1e.kubedeploy.v1.DeploymentPhaseR\x05phase\x12#\n" +
	"\rcurrent_image\x18\x04 \x01(\tR\fcurrentImage\x12%\n" +
	"\x0eready_replicas\x18\x05 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10desired_replicas\x18\x06 \x01(\x05R\x0fdesiredReplicas\x12)\n" +
	"\x10updated_replicas\x18\a \x01(\x05R\x0fupdatedReplicas\x12-\n" +
	"\x12available_replicas\x18\b \x01(\x05R\x11availableReplicas\x12)\n" +
	"\x10current_revision\x18\t \x01(\x03R\x0fcurrentRevision\x12@\n" +
	"\rhealth_status\x18\n" +
	" \x01(\x0e2\x1b.kubedeploy.v1.HealthStatusR\fhealthStatus\x12=\n" +
	"\flast_updated\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12,\n" +
	"\x04pods\x18\f \x03(\v2\x18.kubedeploy.v1.PodStatusR\x04pods\x12\x1e\n" +
	"\n" +
	"conditions\x18\r \x03(\tR\n" +
	"conditions\"\xf8\x01\n" +
	"\tPodStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12#\n" +
	"\rrestart_count\x18\x04 \x01(\x05R\frestartCount\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"\xd9\x01\n" +
	"\x16ListDeploymentsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12_\n" +
	"\x0elabel_selector\x18\x02 \x03(\v28.kubedeploy.v1.ListDeploymentsRequest.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x17ListDeploymentsResponse\x12A\n" +
	"\vdeployments\x18\x01 \x03(\v2\x1f.kubedeploy.v1.DeploymentStatusR\vdeployments\"\x99\x01\n" +
	"\x0fRollbackRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x12'\n" +
	"\x0ftarget_revision\x18\x03 \x01(\x03R\x0etargetRevision\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x85\x02\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x17rolled_back_to_revision\x18\x03 \x01(\x03R\x14rolledBackToRevision\x12%\n" +
	"\x0eprevious_image\x18\x04 \x01(\tR\rpreviousImage\x12%\n" +
	"\x0erestored_image\x18\x05 \x01(\tR\rrestoredImage\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcc\x01\n" +
	"\x12WatchHealthRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x125\n" +
	"\binterval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\binterval\x128\n" +
	"\x06checks\x18\x04 \x03(\v2 .kubedeploy.v1.HealthCheckConfigR\x06checks\"\xa8\x02\n" +
	"\vHealthEvent\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x12B\n" +
	"\x0eoverall_status\x18\x03 \x01(\x0e2\x1b.kubedeploy.v1.HealthStatusR\roverallStatus\x12:\n" +
	"\aresults\x18\x04 \x03(\v2 .kubedeploy.v1.HealthCheckResultR\aresults\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\"\xa7\x03\n" +
	"\x11HealthCheckResult\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.kubedeploy.v1.HealthCheckTypeR\x04type\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.kubedeploy.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x123\n" +
	"\alatency\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\alatency\x129\n" +
	"\n" +
	"checked_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x12J\n" +
	"\bmetadata\x18\a \x03(\v2..kubedeploy.v1.HealthCheckResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x11GetHistoryRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tR\x0edeploymentName\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"U\n" +
	"\x12GetHistoryResponse\x12?\n" +
	"\trevisions\x18\x01 \x03(\v2!.kubedeploy.v1.DeploymentRevisionR\trevisions\"\x9d\x04\n" +
	"\x12DeploymentRevision\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x126\n" +
	"\x06result\x18\x03 \x01(\x0e2\x1e.kubedeploy.v1.DeploymentPhaseR\x06result\x129\n" +
	"\bstrategy\x18\x04 \x01(\x0e2\x1d.kubedeploy.v1.DeployStrategyR\bstrategy\x12;\n" +
	"\vdeployed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vdeployed_by\x18\a \x01(\tR\n" +
	"deployedBy\x12'\n" +
	"\x0frollback_reason\x18\b \x01(\tR\x0erollbackReason\x12E\n" +
	"\x06labels\x18\t \x03(\v2-.kubedeploy.v1.DeploymentRevision.LabelsEntryR\x06labels\x12\x1a\n" +
	"\breplicas\x18\n" +
	" \x01(\x05R\breplicas\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8a\x01\n" +
	"\x0eDeployStrategy\x12\x1f\n" +
	"\x1bDEPLOY_STRATEGY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DEPLOY_STRATEGY_ROLLING\x10\x01\x12\x1a\n" +
	"\x16DEPLOY_STRATEGY_CANARY\x10\x02\x12\x1e\n" +
	"\x1aDEPLOY_STRATEGY_BLUE_GREEN\x10\x03*\xb8\x02\n" +
	"\x0fDeploymentPhase\x12 \n" +
	"\x1cDEPLOYMENT_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DEPLOYMENT_PHASE_PENDING\x10\x01\x12 \n" +
	"\x1cDEPLOYMENT_PHASE_IN_PROGRESS\x10\x02\x12!\n" +
	"\x1dDEPLOYMENT_PHASE_HEALTH_CHECK\x10\x03\x12\x1e\n" +
	"\x1aDEPLOYMENT_PHASE_PROMOTING\x10\x04\x12!\n" +
	"\x1dDEPLOYMENT_PHASE_ROLLING_BACK\x10\x05\x12\x1e\n" +
	"\x1aDEPLOYMENT_PHASE_COMPLETED\x10\x06\x12\x1b\n" +
	"\x17DEPLOYMENT_PHASE_FAILED\x10\a\x12 \n" +
	"\x1cDEPLOYMENT_PHASE_ROLLED_BACK\x10\b*\x9c\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x03\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x04*\xc5\x01\n" +
	"\x0fHealthCheckType\x12!\n" +
	"\x1dHEALTH_CHECK_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fHEALTH_CHECK_TYPE_POD_READINESS\x10\x01\x12#\n" +
	"\x1fHEALTH_CHECK_TYPE_RESTART_COUNT\x10\x02\x12 \n" +
	"\x1cHEALTH_CHECK_TYPE_HTTP_PROBE\x10\x03\x12#\n" +
	"\x1fHEALTH_CHECK_TYPE_CUSTOM_METRIC\x10\x042\x8e\x04\n" +
	"\x11KubeDeployService\x12D\n" +
	"\x06Deploy\x12\x1c.kubedeploy.v1.DeployRequest\x1a\x1a.kubedeploy.v1.DeployEvent0\x01\x12a\n" +
	"\x13GetDeploymentStatus\x12).kubedeploy.v1.GetDeploymentStatusRequest\x1a\x1f.kubedeploy.v1.DeploymentStatus\x12`\n" +
	"\x0fListDeployments\x12%.kubedeploy.v1.ListDeploymentsRequest\x1a&.kubedeploy.v1.ListDeploymentsResponse\x12K\n" +
	"\bRollback\x12\x1e.kubedeploy.v1.RollbackRequest\x1a\x1f.kubedeploy.v1.RollbackResponse\x12N\n" +
	"\vWatchHealth\x12!.kubedeploy.v1.WatchHealthRequest\x1a\x1a.kubedeploy.v1.HealthEvent0\x01\x12Q\n" +
	"\n" +
	"GetHistory\x12 .kubedeploy.v1.GetHistoryRequest\x1a!.kubedeploy.v1.GetHistoryResponseB'Z%github.com/sonu/kube-deploy/api/v1;v1b\x06proto3"

var (
	file_kube_deploy_proto_rawDescOnce sync.Once
	file_kube_deploy_proto_rawDescData []byte
)

func file_kube_deploy_proto_rawDescGZIP() []byte {
	file_kube_deploy_proto_rawDescOnce.Do(func() {
		file_kube_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kube_deploy_proto_rawDesc), len(file_kube_deploy_proto_rawDesc)))
	})
	return file_kube_deploy_proto_rawDescData
}

var file_kube_deploy_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_kube_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_kube_deploy_proto_goTypes = []any{
	(DeployStrategy)(0),                // 0: kubedeploy.v1.DeployStrategy
	(DeploymentPhase)(0),               // 1: kubedeploy.v1.DeploymentPhase
	(HealthStatus)(0),                  // 2: kubedeploy.v1.HealthStatus
	(HealthCheckType)(0),               // 3: kubedeploy.v1.HealthCheckType
	(*DeploymentTarget)(nil),           // 4: kubedeploy.v1.DeploymentTarget
	(*RollingUpdateConfig)(nil),        // 5: kubedeploy.v1.RollingUpdateConfig
	(*CanaryConfig)(nil),               // 6: kubedeploy.v1.CanaryConfig
	(*RollbackPolicy)(nil),             // 7: kubedeploy.v1.RollbackPolicy
	(*HealthCheckConfig)(nil),          // 8: kubedeploy.v1.HealthCheckConfig
	(*DeployRequest)(nil),              // 9: kubedeploy.v1.DeployRequest
	(*DeployEvent)(nil),                // 10: kubedeploy.v1.DeployEvent
	(*GetDeploymentStatusRequest)(nil), // 11: kubedeploy.v1.GetDeploymentStatusRequest
	(*DeploymentStatus)(nil),           // 12: kubedeploy.v1.DeploymentStatus
	(*PodStatus)(nil),                  // 13: kubedeploy.v1.PodStatus
	(*ListDeploymentsRequest)(nil),     // 14: kubedeploy.v1.ListDeploymentsRequest
	(*ListDeploymentsResponse)(nil),    // 15: kubedeploy.v1.ListDeploymentsResponse
	(*RollbackRequest)(nil),            // 16: kubedeploy.v1.RollbackRequest
	(*RollbackResponse)(nil),           // 17: kubedeploy.v1.RollbackResponse
	(*WatchHealthRequest)(nil),         // 18: kubedeploy.v1.WatchHealthRequest
	(*HealthEvent)(nil),                // 19: kubedeploy.v1.HealthEvent
	(*HealthCheckResult)(nil),          // 20: kubedeploy.v1.HealthCheckResult
	(*GetHistoryRequest)(nil),          // 21: kubedeploy.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),         // 22: kubedeploy.v1.GetHistoryResponse
	(*DeploymentRevision)(nil),         // 23: kubedeploy.v1.DeploymentRevision
	nil,                                // 24: kubedeploy.v1.DeployRequest.LabelsEntry
	nil,                                // 25: kubedeploy.v1.DeployRequest.AnnotationsEntry
	nil,                                // 26: kubedeploy.v1.ListDeploymentsRequest.LabelSelectorEntry
	nil,                                // 27: kubedeploy.v1.HealthCheckResult.MetadataEntry
	nil,                                // 28: kubedeploy.v1.DeploymentRevision.LabelsEntry
	(*durationpb.Duration)(nil),        // 29: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),      // 30: google.protobuf.Timestamp
}
var file_kube_deploy_proto_depIdxs = []int32{
	29, // 0: kubedeploy.v1.CanaryConfig.analysis_duration:type_name -> google.protobuf.Duration
	29, // 1: kubedeploy.v1.RollbackPolicy.health_check_interval:type_name -> google.protobuf.Duration
	29, // 2: kubedeploy.v1.RollbackPolicy.health_check_timeout:type_name -> google.protobuf.Duration
	3,  // 3: kubedeploy.v1.HealthCheckConfig.type:type_name -> kubedeploy.v1.HealthCheckType
	29, // 4: kubedeploy.v1.HealthCheckConfig.interval:type_name -> google.protobuf.Duration
	29, // 5: kubedeploy.v1.HealthCheckConfig.timeout:type_name -> google.protobuf.Duration
	4,  // 6: kubedeploy.v1.DeployRequest.target:type_name -> kubedeploy.v1.DeploymentTarget
	0,  // 7: kubedeploy.v1.DeployRequest.strategy:type_name -> kubedeploy.v1.DeployStrategy
	5,  // 8: kubedeploy.v1.DeployRequest.rolling_config:type_name -> kubedeploy.v1.RollingUpdateConfig
	6,  // 9: kubedeploy.v1.DeployRequest.canary_config:type_name -> kubedeploy.v1.CanaryConfig
	7,  // 10: kubedeploy.v1.DeployRequest.rollback_policy:type_name -> kubedeploy.v1.RollbackPolicy
	8,  // 11: kubedeploy.v1.DeployRequest.health_checks:type_name -> kubedeploy.v1.HealthCheckConfig
	24, // 12: kubedeploy.v1.DeployRequest.labels:type_name -> kubedeploy.v1.DeployRequest.LabelsEntry
	25, // 13: kubedeploy.v1.DeployRequest.annotations:type_name -> kubedeploy.v1.DeployRequest.AnnotationsEntry
	1,  // 14: kubedeploy.v1.DeployEvent.phase:type_name -> kubedeploy.v1.DeploymentPhase
	30, // 15: kubedeploy.v1.DeployEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 16: kubedeploy.v1.DeploymentStatus.phase:type_name -> kubedeploy.v1.DeploymentPhase
	2,  // 17: kubedeploy.v1.DeploymentStatus.health_status:type_name -> kubedeploy.v1.HealthStatus
	30, // 18: kubedeploy.v1.DeploymentStatus.last_updated:type_name -> google.protobuf.Timestamp
	13, // 19: kubedeploy.v1.DeploymentStatus.pods:type_name -> kubedeploy.v1.PodStatus
	30, // 20: kubedeploy.v1.PodStatus.start_time:type_name -> google.protobuf.Timestamp
	26, // 21: kubedeploy.v1.ListDeploymentsRequest.label_selector:type_name -> kubedeploy.v1.ListDeploymentsRequest.LabelSelectorEntry
	12, // 22: kubedeploy.v1.ListDeploymentsResponse.deployments:type_name -> kubedeploy.v1.DeploymentStatus
	30, // 23: kubedeploy.v1.RollbackResponse.timestamp:type_name -> google.protobuf.Timestamp
	29, // 24: kubedeploy.v1.WatchHealthRequest.interval:type_name -> google.protobuf.Duration
	8,  // 25: kubedeploy.v1.WatchHealthRequest.checks:type_name -> kubedeploy.v1.HealthCheckConfig
	2,  // 26: kubedeploy.v1.HealthEvent.overall_status:type_name -> kubedeploy.v1.HealthStatus
	20, // 27: kubedeploy.v1.HealthEvent.results:type_name -> kubedeploy.v1.HealthCheckResult
	30, // 28: kubedeploy.v1.HealthEvent.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 29: kubedeploy.v1.HealthCheckResult.type:type_name -> kubedeploy.v1.HealthCheckType
	2,  // 30: kubedeploy.v1.HealthCheckResult.status:type_name -> kubedeploy.v1.HealthStatus
	29, // 31: kubedeploy.v1.HealthCheckResult.latency:type_name -> google.protobuf.Duration
	30, // 32: kubedeploy.v1.HealthCheckResult.checked_at:type_name -> google.protobuf.Timestamp
	27, // 33: kubedeploy.v1.HealthCheckResult.metadata:type_name -> kubedeploy.v1.HealthCheckResult.MetadataEntry
	23, // 34: kubedeploy.v1.GetHistoryResponse.revisions:type_name -> kubedeploy.v1.DeploymentRevision
	1,  // 35: kubedeploy.v1.DeploymentRevision.result:type_name -> kubedeploy.v1.DeploymentPhase
	0,  // 36: kubedeploy.v1.DeploymentRevision.strategy:type_name -> kubedeploy.v1.DeployStrategy
	30, // 37: kubedeploy.v1.DeploymentRevision.deployed_at:type_name -> google.protobuf.Timestamp
	30, // 38: kubedeploy.v1.DeploymentRevision.completed_at:type_name -> google.protobuf.Timestamp
	28, // 39: kubedeploy.v1.DeploymentRevision.labels:type_name -> kubedeploy.v1.DeploymentRevision.LabelsEntry
	9,  // 40: kubedeploy.v1.KubeDeployService.Deploy:input_type -> kubedeploy.v1.DeployRequest
	11, // 41: kubedeploy.v1.KubeDeployService.GetDeploymentStatus:input_type -> kubedeploy.v1.GetDeploymentStatusRequest
	14, // 42: kubedeploy.v1.KubeDeployService.ListDeployments:input_type -> kubedeploy.v1.ListDeploymentsRequest
	16, // 43: kubedeploy.v1.KubeDeployService.Rollback:input_type -> kubedeploy.v1.RollbackRequest
	18, // 44: kubedeploy.v1.KubeDeployService.WatchHealth:input_type -> kubedeploy.v1.WatchHealthRequest
	21, // 45: kubedeploy.v1.KubeDeployService.GetHistory:input_type -> kubedeploy.v1.GetHistoryRequest
	10, // 46: kubedeploy.v1.KubeDeployService.Deploy:output_type -> kubedeploy.v1.DeployEvent
	12, // 47: kubedeploy.v1.KubeDeployService.GetDeploymentStatus:output_type -> kubedeploy.v1.DeploymentStatus
	15, // 48: kubedeploy.v1.KubeDeployService.ListDeployments:output_type -> kubedeploy.v1.ListDeploymentsResponse
	17, // 49: kubedeploy.v1.KubeDeployService.Rollback:output_type -> kubedeploy.v1.RollbackResponse
	19, // 50: kubedeploy.v1.KubeDeployService.WatchHealth:output_type -> kubedeploy.v1.HealthEvent
	22, // 51: kubedeploy.v1.KubeDeployService.GetHistory:output_type -> kubedeploy.v1.GetHistoryResponse
	46, // [46:52] is the sub-list for method output_type
	40, // [40:46] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_kube_deploy_proto_init() }
func file_kube_deploy_proto_init() {
	if File_kube_deploy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kube_deploy_proto_rawDesc), len(file_kube_deploy_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kube_deploy_proto_goTypes,
		DependencyIndexes: file_kube_deploy_proto_depIdxs,
		EnumInfos:         file_kube_deploy_proto_enumTypes,
		MessageInfos:      file_kube_deploy_proto_msgTypes,
	}.Build()
	File_kube_deploy_proto = out.File
	file_kube_deploy_proto_goTypes = nil
	file_kube_deploy_proto_depIdxs = nil
}
